import * as cheerio from "cheerio";
import { fetchText } from "./fetch.mjs";
import HELENA_GAWIN_PHRASES_JSON from "../Frazy.json" with { type: "json" };

const HELENA_GAWIN_PHRASES = Array.isArray(HELENA_GAWIN_PHRASES_JSON)
  ? HELENA_GAWIN_PHRASES_JSON
  : [];
const DEFAULT_FLAGS = { requires_detail_fetch: false, requires_ocr: false, requires_pdf: false };
const REQUIRED_SOURCES = [
  { id:"zck_funerals", name:"ZCK Kraków – Porządek pogrzebów", type:"zck_funerals", url:"https://www.zck-krakow.pl/funerals", enabled:true, distance_km:0, list_url:"https://www.zck-krakow.pl/funerals", ...DEFAULT_FLAGS },
  { id:"puk_pozegnalismy", name:"PUK Kraków – Pożegnaliśmy", type:"puk_pozegnalismy", url:"https://www.puk.krakow.pl/pozegnalismy/", enabled:true, distance_km:4.5, list_url:"https://www.puk.krakow.pl/pozegnalismy/", requires_detail_fetch:true, requires_ocr:false, requires_pdf:false },
  { id:"gabriel_nekrologi", name:"Gabriel24 – Nekrologi", type:"gabriel24_nekrologi", url:"https://www.gabriel24.pl/nekrologi/", enabled:true, distance_km:6.5, list_url:"https://www.gabriel24.pl/nekrologi/", requires_detail_fetch:true, max_detail_pages:50, requires_ocr:false, requires_pdf:false },
  { id:"karawan_nekrologi", name:"Karawan – Nekrologi", type:"karawan_nekrologi", url:"https://karawan.pl/nekrologi/", enabled:true, distance_km:7.5, list_url:"https://karawan.pl/nekrologi/", requires_detail_fetch:true, max_detail_pages:50, requires_ocr:false, requires_pdf:false },
  { id:"salwator_grobonet", name:"Kraków Salwator – Grobonet", type:"grobonet_nekrologi", url:"https://krakowsalwator.grobonet.com/nekrologi.php", enabled:true, distance_km:5.5, list_url:"https://krakowsalwator.grobonet.com/nekrologi.php", base_url:"https://krakowsalwator.grobonet.com/", requires_detail_fetch:true, max_detail_pages:50, requires_ocr:false, requires_pdf:false },
  { id:"debniki_sdb", name:"Parafia św. Stanisława Kostki (Dębniki)", type:"debniki_sdb_pogrzeby", url:"https://debniki.sdb.org.pl/", enabled:true, distance_km:2.5, list_url:"https://debniki.sdb.org.pl/", requires_detail_fetch:true, max_detail_pages:30, requires_ocr:false, requires_pdf:false },
  { id:"podwawelskie_nekrologi", name:"Podwawelskie – Nekrologi", type:"podwawelskie_nekrologi", url:"https://www.podwawelskie.pl/aktualnosci/nekrologi.html", enabled:true, distance_km:2.5, list_url:"https://www.podwawelskie.pl/aktualnosci/nekrologi.html", requires_detail_fetch:true, max_detail_pages:50, requires_ocr:false, requires_pdf:false },
  { id:"sw_jadwiga_pogrzebowe", name:"Parafia św. Jadwigi – Msze święte pogrzebowe", type:"sw_jadwiga_pogrzebowe", url:"https://swietajadwiga.diecezja.pl/parafia/msze-swiete-pogrzebowe", enabled:true, distance_km:6.5, list_url:"https://swietajadwiga.diecezja.pl/parafia/msze-swiete-pogrzebowe", ...DEFAULT_FLAGS },
  { id:"facebook_parafia_debniki", name:"Facebook – Parafia Dębniki", type:"generic_html", url:"https://www.facebook.com/parafiadebniki/?locale=pl_PL", enabled:false, distance_km:2.5 }
];
const NOISE = /(googletagmanager|gtm-|clickcease|iframe|display\s*:\s*none|visibility\s*:\s*hidden|document|window\.|function\(|\bcookie\b|cookies|facebook|pixel|analytics|href=|src=)/i;
const BAD_NAME_WORDS = /(główna|nekrologi|firma|w służbie|kontakt|oferta|usługi|menu|strona główna|polityka prywatności)/i;

const clean = (s)=>String(s??"").replace(/\s+/g," ").trim();
const absoluteUrl=(href,base)=>{try{return new URL(href,base).toString();}catch{return href||base;}};
const nowISO=()=>new Date().toISOString();
const todayIso=()=>new Date().toISOString().slice(0,10);
const uniq=(rows,k)=>[...new Map(rows.map(r=>[k(r),r])).values()];
const parseTime=(t)=>{const text=clean(t); const re=/(?:godz\.?\s*|\bo\s*)?([01]?\d|2[0-3])[.:]([0-5]\d)/gi; let m; while((m=re.exec(text))){ const idx=m.index; const full=m[0]; const hour=m[1].padStart(2,'0'); const min=m[2]; const before=text.slice(Math.max(0,idx-6),idx); const after=text.slice(idx+full.length,idx+full.length+6); if(/[.]|[-]|\//.test(full) && /^[./-]\d{2,4}\b/.test(after)) continue; if(/\d{1,2}[./-]$/.test(before) && /^\d{1,2}([./-]\d{2,4})?\b/.test(after)) continue; if(/\d$/.test(before) && /^\d$/.test(after)) continue; return `${hour}:${min}`; } return null;};
const monthMap={stycznia:1,styczeń:1,lutego:2,luty:2,marca:3,marzec:3,kwietnia:4,kwiecień:4,maja:5,maj:5,czerwca:6,czerwiec:6,lipca:7,lipiec:7,sierpnia:8,sierpień:8,września:9,wrzesień:9,października:10,październik:10,listopada:11,listopad:11,grudnia:12,grudzień:12,v:5};
const parsePolishDateToIso=(raw)=>{const t=clean(raw).toLowerCase(); let m=t.match(/\b(\d{4})-(\d{1,2})-(\d{1,2})\b/); if(m) return `${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`; m=t.match(/\b(\d{1,2})[./-](\d{1,2})[./-](\d{2,4})\b/); if(m){let y=+m[3]; if(y<100) y+=2000; return `${String(y).padStart(4,'0')}-${String(+m[2]).padStart(2,'0')}-${String(+m[1]).padStart(2,'0')}`;} m=t.match(/\b(\d{1,2})\s+([a-ząćęłńóśźż]+|[ivx]+)\s+(\d{4})\b/u); if(m){const mm=monthMap[m[2]]; if(mm) return `${m[3]}-${String(mm).padStart(2,'0')}-${String(+m[1]).padStart(2,'0')}`;} return null;};
function prepareReadableDocument($){$('script,style,iframe,noscript,svg,canvas,form,nav,header,footer,aside,.cookie,.cookies,.cookiebar,.gdpr,.menu,.nav,.navbar,.breadcrumb,.breadcrumbs,.social,.share,.ad,.ads,.banner,.popup,.modal').remove(); return $;}
function extractMainText($, selectors=[]){for(const s of selectors){const tx=clean($(s).first().text()); if(tx) return tx;} return clean($('body').text());}
function cleanTechnicalNoise(text){return clean(String(text||'').split(/\n+/).filter(x=>!NOISE.test(x)).join(' '));}
function nameFromSlug(url){try{let seg=new URL(url).pathname.replace(/\/$/,'').split('/').pop()||''; if(/^(nekrolog|pogrzeb|aktualnosci|category|page|kontakt)$/i.test(seg)) return null; seg=seg.replace(/\d+/g,'').replace(/-/g,' '); return clean(seg).split(' ').filter(Boolean).map(w=>w.charAt(0).toUpperCase()+w.slice(1)).join(' ');}catch{return null;}}
function isBadNameCandidate(name){const n=clean(name); return !n || n.split(' ').length<2 || n.length>80 || BAD_NAME_WORDS.test(n) || NOISE.test(n) || /<[^>]+>|https?:\/\//i.test(n);}
function validateParsedRow(row){if(!row||!clean(row.name)||isBadNameCandidate(row.name)) return false; if(!['death','funeral'].includes(row.kind)) return false; if(!row.source_id||!row.source_name||!row.url) return false; if(NOISE.test(clean(row.note))||NOISE.test(clean(row.place))) return false; return true;}

function parseDetail(text,source,detailUrl,forceFuneral=false){const $=prepareReadableDocument(cheerio.load(text)); const body=extractMainText($,['main','article','.entry-content','.content']); const note=cleanTechnicalNoise(body); const name=(note.match(/(?:Śp\.?\s*)?([A-ZŁŚŻŹĆŃÓ][\p{L}-]+\s+[A-ZŁŚŻŹĆŃÓ][\p{L}-]+)/u)||[])[1]||nameFromSlug(detailUrl); const dd=parsePolishDateToIso((note.match(/zmar[łłaey]?[^^\d]{0,30}([\d./-]{6,10}|\d{1,2}\s+[a-ząćęłńóśźżivx]+\s+\d{4})/iu)||[])[1]||''); const df=parsePolishDateToIso((note.match(/(pogrzeb|uroczysto)[^\d]{0,40}([\d./-]{6,10}|\d{1,2}\s+[a-ząćęłńóśźżivx]+\s+\d{4})/iu)||[])[2]||''); const tm=parseTime(note); const pl=cleanTechnicalNoise((note.match(/(cmentarz[^.\n]*|kaplica[^.\n]*|koś[cś]ci[oó][łl][^.\n]*|parafia[^.\n]*|cm\.[^.\n]*)/i)||[])[1]||source.name); const row={kind:forceFuneral?'funeral':(dd?'death':'funeral'),name,date_death:dd,date_funeral:df,time_funeral:tm,place:pl,source_id:source.id,source_name:source.name,url:detailUrl,source_url:source.url,note:note.slice(0,250)}; return validateParsedRow(row)?row:null;}

function parseGenericList(text,source){const $=cheerio.load(text); return uniq($('a[href]').map((_,a)=>absoluteUrl($(a).attr('href'),source.url)).get().filter(u=>/nekrolog|pogrzeb|zmar|klepsydr|id=/.test(u)).map(url=>({url})),r=>r.url);}
async function parseByListAndDetails(source,forceFuneral=false,listParser=parseGenericList,detailParser=parseDetail){const r=await fetchText(source.list_url||source.url); if(!r.ok) return {rows:[],error:r.error||`HTTP ${r.status}`}; const links=listParser(r.text,source).slice(0,source.max_detail_pages||50); if(!links.length) return {rows:[],error:`${source.name}: nie znaleziono linków szczegółów`}; const rows=[]; for(const l of links){const d=await fetchText(l.url); if(!d.ok) continue; const row=detailParser(d.text,source,l.url,forceFuneral); if(row) rows.push(row);} if(!rows.length) return {rows:[],error:`${source.name}: znaleziono ${links.length} linków, ale zero poprawnych rekordów`}; return {rows:uniq(rows,r=>`${r.kind}|${r.name}|${r.url}`),error:null};}

const parseGabriel24NekrologiHtml=(t,s)=>parseGenericList(t,s).filter(x=>/gabriel24/i.test(x.url)||/nekrolog/i.test(x.url));
const parseGrobonetNekrologiHtml=(t,s)=>{
  const $=prepareReadableDocument(cheerio.load(t));
  return uniq($('a[href]').map((_,a)=>({url:absoluteUrl($(a).attr('href'),s.url),label:clean($(a).text())})).get()
    .filter(x=>/grobonet/i.test(x.url))
    .filter(x=>/(nekrolog|osoba=|id=|index\.php\?s=|klepsydra|nekrologi\.php\?)/i.test(x.url))
    .filter(x=>!/(kontakt|regulamin|polityka|cookie|javascript:|mailto:)/i.test(x.url))
    .map(x=>({url:x.url})),x=>x.url);
};
const parsePodwawelskieNekrologiHtml=(t,s)=>{
  const $=prepareReadableDocument(cheerio.load(t));
  return uniq($('a[href]').map((_,a)=>({url:absoluteUrl($(a).attr('href'),s.url),label:clean($(a).text())})).get()
    .filter(x=>/nekrologi--str-\d+\.html/i.test(x.url) || /^\d+$/.test(x.label))
    .map(x=>({url:x.url})),x=>x.url);
};
const parseKarawanNekrologiHtml=(t,s)=>parseGenericList(t,s).filter(x=>/karawan\.pl\/nekrolog\//i.test(x.url));

function parsePodwawelskieRowsFromListHtml(text, source, pageUrl) {
  const body = cleanTechnicalNoise(extractMainText(prepareReadableDocument(cheerio.load(text)), ['main', 'article', '.entry-content', '.content']));
  const matches = [...body.matchAll(/([A-ZŁŚŻŹĆŃÓ][\p{L}-]+\s+[A-ZŁŚŻŹĆŃÓ][\p{L}-]+)[^\n]{0,120}?(?:ur\.?\s*([\d./-]{6,10}|\d{1,2}\s+[a-ząćęłńóśźżivx]+\s+\d{4}))?[^\n]{0,120}?(?:zm\.?|zmar[łł]\w*)\s*([\d./-]{6,10}|\d{1,2}\s+[a-ząćęłńóśźżivx]+\s+\d{4})/giu)];
  return matches.map((m)=>({
    kind:'death', name:clean(m[1]), date_death:parsePolishDateToIso(m[3])||null, date_funeral:null, time_funeral:null,
    place:source.name, source_id:source.id, source_name:source.name, url:pageUrl, source_url:source.url,
    note:clean(`ur.: ${m[2]||'brak'}; zm.: ${m[3]||'brak'}; Podwawelskie`)
  })).filter(validateParsedRow);
}
function parseGabriel24DetailHtml(text,source,detailUrl){const $=prepareReadableDocument(cheerio.load(text)); const root=$('main,article,.entry-content,.content,.nekrolog,.obituary').first(); const scoped=root.length?root:$('body'); const note=cleanTechnicalNoise(clean(scoped.text())); const h1=cleanTechnicalNoise(scoped.find('h1,h2,.name,.nazwisko').first().text())||cleanTechnicalNoise($('title').text()); const slug=nameFromSlug(detailUrl); const name=[h1,slug].find(x=>x&&!isBadNameCandidate(x)); if(!name||NOISE.test(note)) return null; const df=parsePolishDateToIso((note.match(/(pogrzeb|uroczysto)[^\d]{0,40}([\d./-]{6,10}|\d{1,2}\s+[a-ząćęłńóśźżivx]+\s+\d{4})/iu)||[])[2]||''); const dd=parsePolishDateToIso((note.match(/zmar[łłaey]?[^\d]{0,30}([\d./-]{6,10}|\d{1,2}\s+[a-ząćęłńóśźżivx]+\s+\d{4})/iu)||[])[1]||''); const tm=parseTime(note); const place=cleanTechnicalNoise((note.match(/(cmentarz[^.\n]*|kaplica[^.\n]*|koś[cś]ci[oó][łl][^.\n]*|parafia[^.\n]*)/i)||[])[1]||source.name); const row={kind:dd?'death':'funeral',name,date_death:dd,date_funeral:df,time_funeral:tm,place,source_id:source.id,source_name:source.name,url:detailUrl,source_url:source.url,note:note.slice(0,260)}; return validateParsedRow(row)?row:null;}
function parseGrobonetDetailHtml(text,source,detailUrl){const $=prepareReadableDocument(cheerio.load(text)); const root=$('main,article,.content,.entry-content,.obituary,#nekrolog,#klepsydra,.person-box').first(); const scoped=root.length?root:$('body'); const note=cleanTechnicalNoise(clean(scoped.text())); const name=cleanTechnicalNoise(scoped.find('h1,h2,.name,.nazwisko,.person-name,.title').first().text())||cleanTechnicalNoise((note.match(/(?:Śp\.?|Zmarł[a]?)\s*([A-ZŁŚŻŹĆŃÓ][\p{L}-]+\s+[A-ZŁŚŻŹĆŃÓ][\p{L}-]+)/u)||[])[1])||nameFromSlug(detailUrl); if(!name||isBadNameCandidate(name)) return null; const dd=parsePolishDateToIso((note.match(/(?:zmar[łłaey]?|data zgonu)[^\d]{0,30}([\d./-]{6,10}|\d{1,2}\s+[a-ząćęłńóśźżivx]+\s+\d{4})/iu)||[])[1]||''); const df=parsePolishDateToIso((note.match(/(pogrzeb|ceremonia|uroczysto|pożegnanie|wyprowadzenie)[^\d]{0,40}([\d./-]{6,10}|\d{1,2}\s+[a-ząćęłńóśźżivx]+\s+\d{4})/iu)||[])[2]||''); const tm=parseTime(note); const place=cleanTechnicalNoise((note.match(/(cmentarz[^.\n]*|kaplica[^.\n]*|koś[cś]ci[oó][łl][^.\n]*|sala pożegnań[^.\n]*)/i)||[])[1]||source.name); const row={kind:'funeral',name,date_death:dd||null,date_funeral:df||null,time_funeral:tm,place,source_id:source.id,source_name:source.name,url:detailUrl,source_url:source.url,note:note.slice(0,260)}; return validateParsedRow(row)?row:null;}
function parsePodwawelskieDetailHtml(text,source,detailUrl){const $=prepareReadableDocument(cheerio.load(text)); const root=$('main,article,.entry-content,.content,.post-content,.content-text,.news-content').first(); const scoped=root.length?root:$('body'); const note=cleanTechnicalNoise(clean(scoped.text())); const name=cleanTechnicalNoise(scoped.find('h1,h2,.name,.nazwisko,img[alt]').first().text()||scoped.find('img[alt]').first().attr('alt'))||cleanTechnicalNoise((note.match(/(?:Śp\.?|Zmarł[a]?)\s*([A-ZŁŚŻŹĆŃÓ][\p{L}-]+\s+[A-ZŁŚŻŹĆŃÓ][\p{L}-]+)/u)||[])[1])||nameFromSlug(detailUrl); if(!name||isBadNameCandidate(name)) return null; const funeralChunk=((note.match(/(pogrzeb|msza pogrzebowa|uroczystości pogrzebowe|ostatnie pożegnanie)[^.\n]{0,180}/iu)||[])[0]||''); const df=parsePolishDateToIso((funeralChunk.match(/([\d./-]{6,10}|\d{1,2}\s+[a-ząćęłńóśźżivx]+\s+\d{4})/iu)||[])[1]||''); const tm=parseTime(funeralChunk||note); const place=cleanTechnicalNoise((funeralChunk.match(/(cmentarz[^.\n]*|kaplica[^.\n]*|koś[cś]ci[oó][łl][^.\n]*|parafia[^.\n]*)/i)||[])[1]||(note.match(/(cmentarz[^.\n]*|kaplica[^.\n]*|koś[cś]ci[oó][łl][^.\n]*|parafia[^.\n]*)/i)||[])[1]||source.name); const row={kind:'funeral',name,date_death:null,date_funeral:df||null,time_funeral:tm,place,source_id:source.id,source_name:source.name,url:detailUrl,source_url:source.url,note:note.slice(0,260)}; return validateParsedRow(row)?row:null;}
function parseKarawanDetailHtml(text,source,detailUrl){const $=prepareReadableDocument(cheerio.load(text)); const mainText=cleanTechnicalNoise(extractMainText($,['main','article','.entry-content','.page-content','.post-content','.single-content','.content','.nekrolog','.nekrolog-content','.obituary','.obituary-content','[class*="nekrolog"]','[class*="obituary"]'])); const title=cleanTechnicalNoise($('title').text().replace(/\s*[\-|–].*$/,'')); const h1=cleanTechnicalNoise($('main h1, article h1, h1').first().text()); let name=[h1,title,nameFromSlug(detailUrl)].find(x=>x&&!isBadNameCandidate(x)); if(!name) return null; const dateChunk=(mainText.match(/(\d{4}-\d{1,2}-\d{1,2}|\d{1,2}[./-]\d{1,2}[./-]\d{2,4}|\d{1,2}\s+[a-ząćęłńóśźżivx]+\s+\d{4})/iu)||[])[1]||''; const df=parsePolishDateToIso(dateChunk)||null; const tm=parseTime(mainText); const place=cleanTechnicalNoise((mainText.match(/(cmentarz[^.\n]*|kaplica[^.\n]*|koś[cś]ci[oó][łl][^.\n]*|parafia[^.\n]*|cm\.[^.\n]*)/i)||[])[1]||source.name); const row={kind:df?'funeral':'death',name,date_death:null,date_funeral:df,time_funeral:tm,place,source_id:source.id,source_name:source.name,url:detailUrl,source_url:source.url,note:mainText.slice(0,260)}; return validateParsedRow(row)?row:null;}

const parseGabriel24Nekrologi=(s)=>parseByListAndDetails(s,false,parseGabriel24NekrologiHtml,parseGabriel24DetailHtml);
async function parseGrobonetNekrologi(source){
  const r=await fetchText(source.list_url||source.url);
  if(!r.ok) return {rows:[],error:r.error||`HTTP ${r.status}`, diagnostics:{http_status:r.status,parser_status:r.status===403?'blocked':'http_error'}};
  const links=parseGrobonetNekrologiHtml(r.text,source).slice(0,source.max_detail_pages||50);
  if(!links.length){
    const looksLikeGrobonet=/grobonet|nekrologi|cmentarz/i.test(r.text);
    if(looksLikeGrobonet) return {rows:[],error:null,diagnostics:{http_status:r.status,candidate_links:0,accepted_rows:0,parser_status:'empty'}};
    return {rows:[],error:`${source.name}: nie znaleziono linków szczegółów`,diagnostics:{http_status:r.status,candidate_links:0,accepted_rows:0,parser_status:'parser_broken'}};
  }
  const rows=[]; for(const l of links){const d=await fetchText(l.url); if(!d.ok) continue; const row=parseGrobonetDetailHtml(d.text,source,l.url); if(row) rows.push(row);} 
  if(!rows.length) return {rows:[],error:`${source.name}: znaleziono ${links.length} linków, ale zero poprawnych rekordów`,diagnostics:{http_status:r.status,candidate_links:links.length,accepted_rows:0,parser_status:'parser_broken'}};
  return {rows:uniq(rows,r=>`${r.kind}|${r.name}|${r.url}`),error:null,diagnostics:{http_status:r.status,candidate_links:links.length,accepted_rows:rows.length,parser_status:'ok'}};
}
async function parsePodwawelskieNekrologi(source){
  const r=await fetchText(source.list_url||source.url);
  if(!r.ok) return {rows:[],error:r.error||`HTTP ${r.status}`, diagnostics:{http_status:r.status,parser_status:r.status===403?'blocked':'http_error'}};
  const pages=[source.list_url||source.url,...parsePodwawelskieNekrologiHtml(r.text,source).map(l=>l.url)].slice(0,source.max_detail_pages||50);
  const rows=[];
  for(const pageUrl of uniq(pages,u=>u)){
    const pr=pageUrl=== (source.list_url||source.url) ? r : await fetchText(pageUrl);
    if(!pr.ok) continue;
    rows.push(...parsePodwawelskieRowsFromListHtml(pr.text,source,pageUrl));
  }
  const deduped=uniq(rows,r=>`${r.source_id}|${r.name}|${r.date_death||''}|${r.note||''}`);
  return {rows:deduped,error:null,diagnostics:{http_status:r.status,candidate_pages:pages.length,accepted_rows:deduped.length,parser_status:deduped.length?'ok':'empty'}};
}
const parseKarawanNekrologi=(s)=>parseByListAndDetails(s,false,parseKarawanNekrologiHtml,parseKarawanDetailHtml);

const parseDebnikiSdbPogrzebyHtml=(text,source)=>{const $=prepareReadableDocument(cheerio.load(text)); return uniq($('a[href]').map((_,a)=>({url:absoluteUrl($(a).attr('href'),source.url),label:clean($(a).text())})).get().filter(x=>/pogrzeb|zmar|nekrolog|aktualn|intenc/i.test(`${x.url} ${x.label}`)),x=>x.url);};
function parseDebnikiSdbDetailHtml(text,source,detailUrl){const $=prepareReadableDocument(cheerio.load(text)); const note=cleanTechnicalNoise(extractMainText($,['main','article','.entry-content','.content'])); const hasFuneral=/(pogrzeb|pogrzebowa|msza\s+święta\s+pogrzebowa|uroczystości\s+pogrzebowe)/i.test(note); const hasDeathMention=/(w minionym tygodniu pożegnaliśmy|pożegnaliśmy z naszej wspólnoty|śp\.?|zmarł|zmarła)/i.test(note); if(!hasFuneral && !hasDeathMention) return null; if(/^\+\s*[A-ZŁŚŻŹĆŃÓ]/u.test(clean(note))) return null; const name=(note.match(/(?:za\s+śp\.?\s*|śp\.?\s*|pogrzebowa\s+)([A-ZŁŚŻŹĆŃÓ][\p{L}-]+\s+[A-ZŁŚŻŹĆŃÓ][\p{L}-]+)/iu)||[])[1]||nameFromSlug(detailUrl); const df=parsePolishDateToIso((note.match(/([\d]{1,2}[./-][\d]{1,2}[./-][\d]{2,4}|\d{1,2}\s+[a-ząćęłńóśźżivx]+\s+\d{4}|\d{4}-\d{1,2}-\d{1,2})/iu)||[])[1]||''); const tm=parseTime(note); const row={kind:hasFuneral?'funeral':'death',name,date_death:hasFuneral?null:(parsePolishDateToIso((note.match(/zmar[łłaey]?[^\d]{0,30}([\d./-]{6,10}|\d{1,2}\s+[a-ząćęłńóśźżivx]+\s+\d{4})/iu)||[])[1]||'')||null),date_funeral:hasFuneral?df:null,time_funeral:hasFuneral?tm:null,place:source.name,source_id:source.id,source_name:source.name,url:detailUrl,source_url:source.url,note:note.slice(0,260)}; return validateParsedRow(row)?row:null;}
async function parseDebnikiSdbPogrzeby(source){const r=await fetchText(source.list_url||source.url); if(!r.ok) return {rows:[],error:r.error||`HTTP ${r.status}`}; const links=parseDebnikiSdbPogrzebyHtml(r.text,source).slice(0,source.max_detail_pages||30); if(!links.length) return {rows:[],error:'Dębniki SDB: nie znaleziono linków szczegółów'}; const rows=[]; for(const l of links){const d=await fetchText(l.url); if(!d.ok) continue; const row=parseDebnikiSdbDetailHtml(d.text,source,l.url); if(row) rows.push(row);} if(!rows.length) return {rows:[],error:`Dębniki SDB: pobrano ${links.length} podstron, ale brak jednoznacznych danych`,diagnostics:{parser_status:'empty',candidate_links:links.length,accepted_rows:0}}; return {rows:uniq(rows,r=>`${r.kind}|${r.name}|${r.url}`),error:null,diagnostics:{parser_status:'ok',candidate_links:links.length,accepted_rows:rows.length}};}
function parseSwJadwigaPogrzeboweHtml(text,source){const t=cleanTechnicalNoise(clean(cheerio.load(text)('body').text())); const m=[...t.matchAll(/(\d{1,2}[./-]\d{1,2}[./-]\d{2,4}|\d{1,2}\s+[a-ząćęłńóśźżivx]+\s+\d{4}).{0,40}?((?:[01]?\d|2[0-3])[.:][0-5]\d).{0,120}?([A-ZŁŚŻŹĆŃÓ][\p{L}-]+\s+[A-ZŁŚŻŹĆŃÓ][\p{L}-]+)/giu)]; return m.map(x=>({kind:'funeral',name:x[3],date_death:null,date_funeral:parsePolishDateToIso(x[1]),time_funeral:parseTime(x[2]),place:source.name,source_id:source.id,source_name:source.name,url:source.url,source_url:source.url,note:`Msza święta pogrzebowa: ${x[0].slice(0,120)}`})).filter(validateParsedRow);}

function parseZckFuneralsHtml(text,source){const $=cheerio.load(text); const lines=$('body').find('h1,h2,h3,h4,p,li,div,td,span,strong,b').map((_,e)=>clean($(e).text())).get().filter(Boolean); let date=clean($.text()).match(/\b\d{4}-\d{2}-\d{2}\b/)?.[0]||todayIso(); const fallback=!clean($.text()).match(/\b\d{4}-\d{2}-\d{2}\b/); let cem=''; const rows=[]; for(let i=0;i<lines.length;i++){const l=lines[i]; if(/cmentarz/i.test(l)){cem=l; continue;} const tm=parseTime(l); if(!tm) continue; const combined=[l,lines[i+1],lines[i+2]].filter(Boolean).join(' | '); const name=(combined.match(/([A-ZŁŚŻŹĆŃÓ][\p{L}-]+\s+[A-ZŁŚŻŹĆŃÓ][\p{L}-]+)/u)||[])[1]||clean(lines[i+2]||''); const place=clean((l.replace(tm,'').split('|')[0]||lines[i+1]||'').replace(name,'')); const row={kind:'funeral',name,date_death:null,date_funeral:date,time_funeral:tm,place:[place,cem].filter(Boolean).join(' – '),source_id:source.id,source_name:source.name,url:source.url,source_url:source.url,note:fallback?`ZCK fallback date; ${cem}`:`ZCK: ${cem}`}; if(validateParsedRow(row)) rows.push(row);} return uniq(rows,r=>`${r.name}|${r.date_funeral}|${r.time_funeral}|${r.place}`)}
async function parseZckFunerals(source){const r=await fetchText(source.list_url||source.url); if(!r.ok) return {rows:[],error:r.error||`HTTP ${r.status}`}; return {rows:parseZckFuneralsHtml(r.text,source),error:null};}
function parsePukPozegnalismyHtml(text,source){const $=cheerio.load(text); const rows=[]; $('.results-klepsydra .eklepsydra').each((_,c)=>{const root=$(c); const h=clean(root.find('p').first().text()); const name=clean(root.find('p.fs-28, p.h-80').first().text().replace(/^ŚP\.?\s*/i,'')); const f=clean(root.find('p').filter((_,e)=>/data pogrzebu/i.test($(e).text())).first().text()); const dd=parsePolishDateToIso(h), df=parsePolishDateToIso(f), tf=parseTime(f); const url=absoluteUrl(root.find('a.btn.link').attr('href')||source.url, source.url); const death={kind:'death',name,date_death:dd,date_funeral:df,time_funeral:tf,place:source.name,source_id:source.id,source_name:source.name,url,source_url:source.url,note:clean(`${h} | ${f}`)}; const funeral={...death,kind:'funeral',note:h}; if(validateParsedRow(death)) rows.push(death); if(df&&validateParsedRow(funeral)) rows.push(funeral);}); return uniq(rows,r=>`${r.kind}|${r.name}|${r.url}|${r.date_death}|${r.date_funeral}`)}
async function parsePukPozegnalismy(source){const r=await fetchText(source.list_url||source.url); if(!r.ok) return {rows:[],error:r.error||`HTTP ${r.status}`}; return {rows:parsePukPozegnalismyHtml(r.text,source),error:null};}
async function parseSwJadwigaPogrzebowe(source){const r=await fetchText(source.list_url||source.url); if(!r.ok) return {rows:[],error:r.error||`HTTP ${r.status}`}; return {rows:parseSwJadwigaPogrzeboweHtml(r.text,source),error:null};}

function mergeRequiredSources(existing){const list=Array.isArray(existing)?existing:[];const byId=new Map(list.map(s=>[s.id,s])); for(const r of REQUIRED_SOURCES){byId.set(r.id,{...r,...byId.get(r.id)});} return [...byId.values()];}
const isIntentionLikeSource=()=>false; const isIntentionLikeRow=()=>false; const isEligibleDeathRow=(r)=>r?.kind==='death'; const resolveJobOutcome=({recentDeaths,upcomingFunerals,refreshErrors})=> (recentDeaths+upcomingFunerals<=0?{status:'error',ok:false,errorMessage:(refreshErrors||[]).join(' | ')||'Brak prawidłowych wpisów w odświeżaniu'}:(refreshErrors||[]).length?{status:'done_with_errors',ok:true,errorMessage:refreshErrors.join(' | ')}:{status:'done',ok:true,errorMessage:null});
const buildFallbackSummaryForHelena=()=>({text:'Helena Gawin - brak informacji',date_death:null,date_funeral:null,urls:[]}); const isMeaningfulRow=(r)=>!!clean(r?.name||r?.note);
async function parseGenericHtml(source){return {rows:[],error:`Brak parsera specyficznego dla source_id=${source.id}`};}
async function parseSource(source){switch(source.type){case 'zck_funerals':return parseZckFunerals(source);case 'puk_pozegnalismy':return parsePukPozegnalismy(source);case 'gabriel24_nekrologi':return parseGabriel24Nekrologi(source);case 'karawan_nekrologi':return parseKarawanNekrologi(source);case 'grobonet_nekrologi':return parseGrobonetNekrologi(source);case 'podwawelskie_nekrologi':return parsePodwawelskieNekrologi(source);case 'debniki_sdb_pogrzeby':return parseDebnikiSdbPogrzeby(source);case 'sw_jadwiga_pogrzebowe':return parseSwJadwigaPogrzebowe(source);case 'intencje_plus':return {rows:[],error:null};case 'generic_html':return parseGenericHtml(source);default:return {rows:[],error:`Nieznany parser type=${source.type}`};}}
export {HELENA_GAWIN_PHRASES,REQUIRED_SOURCES,clean,nowISO,parsePolishDateToIso,parseTime,prepareReadableDocument,extractMainText,cleanTechnicalNoise,nameFromSlug,isBadNameCandidate,validateParsedRow,parseZckFunerals,parseZckFuneralsHtml,parsePukPozegnalismy,parsePukPozegnalismyHtml,parseGabriel24Nekrologi,parseGabriel24NekrologiHtml,parseGabriel24DetailHtml,parseKarawanNekrologi,parseKarawanNekrologiHtml,parseKarawanDetailHtml,parseGrobonetNekrologi,parseGrobonetNekrologiHtml,parseGrobonetDetailHtml,parsePodwawelskieNekrologi,parsePodwawelskieNekrologiHtml,parsePodwawelskieRowsFromListHtml,parsePodwawelskieDetailHtml,parseDebnikiSdbPogrzeby,parseDebnikiSdbPogrzebyHtml,parseDebnikiSdbDetailHtml,parseSwJadwigaPogrzebowe,parseSwJadwigaPogrzeboweHtml,parseGenericHtml,parseSource,isIntentionLikeSource,isIntentionLikeRow,isEligibleDeathRow,mergeRequiredSources,resolveJobOutcome,buildFallbackSummaryForHelena,isMeaningfulRow};
