import * as cheerio from "cheerio";
import { fetchText } from "./fetch.mjs";

const HELENA_GAWIN_PHRASES = ["Helena Gawin"];
const DEFAULT_FLAGS = { requires_detail_fetch: false, requires_ocr: false, requires_pdf: false };
const REQUIRED_SOURCES = [
  { id:"zck_funerals", name:"ZCK Kraków – Porządek pogrzebów", type:"zck_funerals", url:"https://www.zck-krakow.pl/funerals", enabled:true, distance_km:0, list_url:"https://www.zck-krakow.pl/funerals", ...DEFAULT_FLAGS },
  { id:"puk_pozegnalismy", name:"PUK Kraków – Pożegnaliśmy", type:"puk_pozegnalismy", url:"https://www.puk.krakow.pl/pozegnalismy/", enabled:true, distance_km:4.5, list_url:"https://www.puk.krakow.pl/pozegnalismy/", requires_detail_fetch:true, requires_ocr:false, requires_pdf:false },
  { id:"gabriel_nekrologi", name:"Gabriel24 – Nekrologi", type:"gabriel24_nekrologi", url:"https://www.gabriel24.pl/nekrologi/", enabled:true, distance_km:6.5, list_url:"https://www.gabriel24.pl/nekrologi/", requires_detail_fetch:true, max_detail_pages:50, requires_ocr:false, requires_pdf:false },
  { id:"karawan_nekrologi", name:"Karawan – Nekrologi", type:"karawan_nekrologi", url:"https://karawan.pl/nekrologi/", enabled:true, distance_km:7.5, list_url:"https://karawan.pl/nekrologi/", requires_detail_fetch:true, max_detail_pages:50, requires_ocr:false, requires_pdf:false },
  { id:"salwator_grobonet", name:"Kraków Salwator – Grobonet", type:"grobonet_nekrologi", url:"https://krakowsalwator.grobonet.com/nekrologi.php", enabled:true, distance_km:5.5, list_url:"https://krakowsalwator.grobonet.com/nekrologi.php", base_url:"https://krakowsalwator.grobonet.com/", requires_detail_fetch:true, max_detail_pages:50, requires_ocr:false, requires_pdf:false },
  { id:"debniki_sdb", name:"Parafia św. Stanisława Kostki (Dębniki)", type:"debniki_sdb_pogrzeby", url:"https://debniki.sdb.org.pl/", enabled:true, distance_km:2.5, list_url:"https://debniki.sdb.org.pl/", requires_detail_fetch:true, max_detail_pages:30, requires_ocr:false, requires_pdf:false },
  { id:"podwawelskie_nekrologi", name:"Podwawelskie – Nekrologi", type:"podwawelskie_nekrologi", url:"https://www.podwawelskie.pl/aktualnosci/nekrologi.html", enabled:true, distance_km:2.5, list_url:"https://www.podwawelskie.pl/aktualnosci/nekrologi.html", requires_detail_fetch:true, max_detail_pages:50, requires_ocr:false, requires_pdf:false },
  { id:"sw_jadwiga_pogrzebowe", name:"Parafia św. Jadwigi – Msze święte pogrzebowe", type:"sw_jadwiga_pogrzebowe", url:"https://swietajadwiga.diecezja.pl/parafia/msze-swiete-pogrzebowe", enabled:true, distance_km:6.5, list_url:"https://swietajadwiga.diecezja.pl/parafia/msze-swiete-pogrzebowe", ...DEFAULT_FLAGS },
  { id:"facebook_parafia_debniki", name:"Facebook – Parafia Dębniki", type:"generic_html", url:"https://www.facebook.com/parafiadebniki/?locale=pl_PL", enabled:false, distance_km:2.5 }
];
const clean=(s)=>String(s??"").replace(/\s+/g," ").trim();
const absoluteUrl=(href,base)=>{try{return new URL(href,base).toString();}catch{return href||base;}};
const nowISO=()=>new Date().toISOString();
const uniq=(rows,k)=>[...new Map(rows.map(r=>[k(r),r])).values()];
const parsePolishDateToIso=(r)=>{const m=clean(r).match(/(\d{1,2})[./-](\d{1,2})[./-](\d{2,4})/); if(!m) return null; let y=+m[3]; if(y<100)y+=2000; return `${String(y).padStart(4,'0')}-${String(+m[2]).padStart(2,'0')}-${String(+m[1]).padStart(2,'0')}`;};
const todayIso=()=>new Date().toISOString().slice(0,10);
function mergeRequiredSources(existing){const list=Array.isArray(existing)?existing:[];const byId=new Map(list.map(s=>[s.id,s])); for(const r of REQUIRED_SOURCES){byId.set(r.id,{...r,...byId.get(r.id)});} return [...byId.values()];}
const isIntentionLikeSource=()=>false; const isIntentionLikeRow=()=>false; const isEligibleDeathRow=(r)=>r?.kind==='death'; const resolveJobOutcome=({recentDeaths,upcomingFunerals,refreshErrors})=> (recentDeaths+upcomingFunerals<=0?{status:'error',ok:false,errorMessage:(refreshErrors||[]).join(' | ')||'Brak prawidłowych wpisów w odświeżaniu'}:(refreshErrors||[]).length?{status:'done_with_errors',ok:true,errorMessage:refreshErrors.join(' | ')}:{status:'done',ok:true,errorMessage:null});
const buildFallbackSummaryForHelena=()=>({text:'Helena Gawin - brak informacji',date_death:null,date_funeral:null,urls:[]}); const isMeaningfulRow=(r)=>!!clean(r?.name||r?.note);

function parseZckFuneralsHtml(text,source){const $=cheerio.load(text); const lines=$('body').find('h1,h2,h3,h4,p,li,div,td,span,strong,b').map((_,e)=>clean($(e).text())).get().filter(Boolean); let date=clean($.text()).match(/\b\d{4}-\d{2}-\d{2}\b/)?.[0]||todayIso(); const fallback=!clean($.text()).match(/\b\d{4}-\d{2}-\d{2}\b/); let cem=''; const rows=[]; for(let i=0;i<lines.length;i++){const l=lines[i]; if(/cmentarz/i.test(l)){cem=l; continue;} const tm=l.match(/\b([01]?\d|2[0-3]):[0-5]\d\b/)?.[0]; if(!tm) continue; const next=[lines[i+1],lines[i+2]].filter(Boolean); const combined=[l,...next].join(' | '); const name=(combined.match(/([A-ZŁŚŻŹĆŃÓ][\p{L}-]+\s+[A-ZŁŚŻŹĆŃÓ][\p{L}-]+)/u)||[])[1]||clean(lines[i+2]||''); const place=clean((l.replace(tm,'').split('|')[0]||lines[i+1]||'').replace(name,'')); if(name) rows.push({kind:'funeral',name,date_death:null,date_funeral:date,time_funeral:tm,place:[place,cem].filter(Boolean).join(' – '),source_id:source.id,source_name:source.name,url:source.url,source_url:source.url,note:fallback?`ZCK fallback date; ${cem}`:`ZCK: ${cem}`}); } return uniq(rows,r=>`${r.name}|${r.date_funeral}|${r.time_funeral}|${r.place}`)}
async function parseZckFunerals(source){const r=await fetchText(source.list_url||source.url); if(!r.ok) return {rows:[],error:r.error||`HTTP ${r.status}`}; return {rows:parseZckFuneralsHtml(r.text,source),error:null};}

function parsePukPozegnalismyHtml(text,source){const $=cheerio.load(text); const rows=[]; $('.results-klepsydra .eklepsydra').each((_,c)=>{const root=$(c); const h=clean(root.find('p').first().text()); const name=clean(root.find('p.fs-28, p.h-80').first().text().replace(/^ŚP\.?\s*/i,'')); const f=clean(root.find('p').filter((_,e)=>/data pogrzebu/i.test($(e).text())).first().text()); const dd=parsePolishDateToIso(h), df=parsePolishDateToIso(f), tf=f.match(/\b([01]?\d|2[0-3]):[0-5]\d\b/)?.[0]||null; const url=absoluteUrl(root.find('a.btn.link').attr('href')||source.url, source.url); if(!name||(!dd&&!df)) return; rows.push({kind:'death',name,date_death:dd,date_funeral:df,time_funeral:tf,place:source.name,source_id:source.id,source_name:source.name,url,source_url:source.url,note:clean(`${h} | ${f}`)}); if(df) rows.push({kind:'funeral',name,date_death:dd,date_funeral:df,time_funeral:tf,place:source.name,source_id:source.id,source_name:source.name,url,source_url:source.url,note:h});}); return uniq(rows,r=>`${r.kind}|${r.name}|${r.url}|${r.date_death}|${r.date_funeral}`)}
async function parsePukPozegnalismy(source){const r=await fetchText(source.list_url||source.url); if(!r.ok) return {rows:[],error:r.error||`HTTP ${r.status}`}; return {rows:parsePukPozegnalismyHtml(r.text,source),error:null};}

function parseGenericList(text,source){const $=cheerio.load(text); return uniq($('a[href]').map((_,a)=>absoluteUrl($(a).attr('href'),source.url)).get().filter(u=>/nekrolog|pogrzeb|zmar|klepsydr|id=/.test(u)).map(url=>({url})),r=>r.url);}
function parseDetail(text,source,detailUrl,forceFuneral=false){const t=clean(cheerio.load(text)('body').text()); const name=(t.match(/(?:Śp\.?\s*)?([A-ZŁŚŻŹĆŃÓ][\p{L}-]+\s+[A-ZŁŚŻŹĆŃÓ][\p{L}-]+)/u)||[])[1]||null; const dd=parsePolishDateToIso((t.match(/zmar[łłaey]?[^\d]{0,30}(\d{1,2}[./-]\d{1,2}[./-]\d{2,4})/i)||[])[1]||''); const df=parsePolishDateToIso((t.match(/(pogrzeb|uroczysto)[^\d]{0,30}(\d{1,2}[./-]\d{1,2}[./-]\d{2,4})/i)||[])[2]||''); const tm=t.match(/\b([01]?\d|2[0-3]):[0-5]\d\b/)?.[0]||null; const pl=(t.match(/(cmentarz[^.\n]*|kaplica[^.\n]*|koś[cś]ci[oó][łl][^.\n]*)/i)||[])[1]||source.name; if(!name) return null; return {kind:forceFuneral?'funeral':(dd?'death':'funeral'),name,date_death:dd,date_funeral:df,time_funeral:tm,place:clean(pl),source_id:source.id,source_name:source.name,url:detailUrl,source_url:source.url,note:t.slice(0,180)};}
async function parseByListAndDetails(source,forceFuneral=false){const r=await fetchText(source.list_url||source.url); if(!r.ok) return {rows:[],error:r.error||`HTTP ${r.status}`}; const links=parseGenericList(r.text,source).slice(0,source.max_detail_pages||50); const rows=[]; for(const l of links){const d=await fetchText(l.url); if(!d.ok) continue; const row=parseDetail(d.text,source,l.url,forceFuneral); if(row) rows.push(row);} return {rows:uniq(rows,r=>`${r.kind}|${r.name}|${r.url}`),error:null};}
const parseGabriel24NekrologiHtml=parseGenericList; const parseKarawanNekrologiHtml=parseGenericList; const parseGrobonetNekrologiHtml=parseGenericList; const parsePodwawelskieNekrologiHtml=parseGenericList;
const parseGabriel24DetailHtml=parseDetail; const parseKarawanDetailHtml=parseDetail; const parseGrobonetDetailHtml=parseDetail; const parsePodwawelskieDetailHtml=parseDetail;
const parseGabriel24Nekrologi=(s)=>parseByListAndDetails(s); const parseKarawanNekrologi=(s)=>parseByListAndDetails(s); const parseGrobonetNekrologi=(s)=>parseByListAndDetails(s); const parsePodwawelskieNekrologi=(s)=>parseByListAndDetails(s);
const parseDebnikiSdbPogrzebyHtml=(text,source)=>{const t=clean(cheerio.load(text)('body').text()); if(/\+\s*[A-Z]/.test(t)&&!/pogrzeb|msza\s+święta\s+pogrzebowa/i.test(t)) return []; if(!/pogrzeb|zmar[łła]|śp\.?|msza\s+święta\s+pogrzebowa/i.test(t)) return []; const row=parseDetail(text,source,source.url,true); return row?[row]:[];};
async function parseDebnikiSdbPogrzeby(source){const r=await fetchText(source.list_url||source.url); if(!r.ok) return {rows:[],error:r.error||`HTTP ${r.status}`}; return {rows:parseDebnikiSdbPogrzebyHtml(r.text,source),error:null};}
function parseSwJadwigaPogrzeboweHtml(text,source){const t=clean(cheerio.load(text)('body').text()); const m=[...t.matchAll(/(\d{1,2}[./-]\d{1,2}[./-]\d{2,4}).{0,40}?((?:[01]?\d|2[0-3]):[0-5]\d).{0,80}?([A-ZŁŚŻŹĆŃÓ][\p{L}-]+\s+[A-ZŁŚŻŹĆŃÓ][\p{L}-]+)/gu)]; return m.map(x=>({kind:'funeral',name:x[3],date_death:null,date_funeral:parsePolishDateToIso(x[1]),time_funeral:x[2],place:source.name,source_id:source.id,source_name:source.name,url:source.url,source_url:source.url,note:`Msza święta pogrzebowa: ${x[0].slice(0,120)}`}));}
async function parseSwJadwigaPogrzebowe(source){const r=await fetchText(source.list_url||source.url); if(!r.ok) return {rows:[],error:r.error||`HTTP ${r.status}`}; return {rows:parseSwJadwigaPogrzeboweHtml(r.text,source),error:null};}
async function parseGenericHtml(source){return {rows:[],error:`Brak parsera specyficznego dla source_id=${source.id}`};}
async function parseSource(source){switch(source.type){case 'zck_funerals':return parseZckFunerals(source);case 'puk_pozegnalismy':return parsePukPozegnalismy(source);case 'gabriel24_nekrologi':return parseGabriel24Nekrologi(source);case 'karawan_nekrologi':return parseKarawanNekrologi(source);case 'grobonet_nekrologi':return parseGrobonetNekrologi(source);case 'podwawelskie_nekrologi':return parsePodwawelskieNekrologi(source);case 'debniki_sdb_pogrzeby':return parseDebnikiSdbPogrzeby(source);case 'sw_jadwiga_pogrzebowe':return parseSwJadwigaPogrzebowe(source);case 'intencje_plus':return {rows:[],error:null};case 'generic_html':return parseGenericHtml(source);default:return {rows:[],error:`Nieznany parser type=${source.type}`};}}
export {HELENA_GAWIN_PHRASES,REQUIRED_SOURCES,clean,nowISO,parseZckFunerals,parseZckFuneralsHtml,parsePukPozegnalismy,parsePukPozegnalismyHtml,parseGabriel24Nekrologi,parseGabriel24NekrologiHtml,parseGabriel24DetailHtml,parseKarawanNekrologi,parseKarawanNekrologiHtml,parseKarawanDetailHtml,parseGrobonetNekrologi,parseGrobonetNekrologiHtml,parseGrobonetDetailHtml,parsePodwawelskieNekrologi,parsePodwawelskieNekrologiHtml,parsePodwawelskieDetailHtml,parseDebnikiSdbPogrzeby,parseDebnikiSdbPogrzebyHtml,parseSwJadwigaPogrzebowe,parseSwJadwigaPogrzeboweHtml,parseGenericHtml,parseSource,isIntentionLikeSource,isIntentionLikeRow,isEligibleDeathRow,mergeRequiredSources,resolveJobOutcome,buildFallbackSummaryForHelena,isMeaningfulRow};
